# [Advent Of Code 2015/15](https://adventofcode.com/2015/day/15)

Launch this notebook: https://datalore.jetbrains.com/view/notebook/5rVU0OC2dt9WbbfSPn1MhT


In [29]:
import sys
!{sys.executable} -m pip install --upgrade pip > /dev/null
!{sys.executable} -m pip install numpy scipy > /dev/null

import numpy as np
from scipy.optimize import minimize
import re

input_file = "15_test.txt"

matchRe = re.compile(r'^(?P<name>\w+): '
                     r'capacity (?P<capacity>-?\d+), '
                     r'durability (?P<durability>-?\d+), '
                     r'flavor (?P<flavor>-?\d+), '
                     r'texture (?P<texture>-?\d+), '
                     r'calories (?P<calories>-?\d+)$')


def list_props(str_line: str) -> list:
    m = matchRe.match(str_line)
    return list(map(int, m.groups()[1::]))


with open(input_file) as f:
    components = list(map(list_props, f))

# print(components)

# strip calories column
components = np.delete(components, 4, 1)
print(components)


[[-1 -2  6  3]
 [ 2  3 -2 -1]]


In [30]:
print(np.transpose(components))


def calc_score(weights: list) -> int:
    if len(components) != len(weights):
        return 0

    # Multiply components matrix × weights matrix, e.g. calc_score([44, 56]):
    # capacity of 44*-1 + 56*2 = 68
    # durability of 44*-2 + 56*3 = 80
    # flavor of 44*6 + 56*-2 = 152
    # texture of 44*3 + 56*-1 = 76
    properties = np.matmul(np.transpose(components), weights)

    # If any properties had produced a negative total,
    # it would have instead become zero,
    # causing the whole score to multiply to zero.
    for number in properties:
        if number < 0:
            return 0

    # Get product of the resulting matrix.
    # e.g.: 68 * 80 * 152 * 76
    product = np.prod(properties)
    return product


def sum_weights(weights: list):
    return np.sum(weights)


weights = [44, 56]

print(sum_weights(weights))
total_score = calc_score(weights)
print(total_score)

[[-1  2]
 [-2  3]
 [ 6 -2]
 [ 3 -1]]
100
62842880
